ALTER TABLE __DOCUMENTS_TABLE__
  ADD COLUMN IF NOT EXISTS owner_user_id TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS workspace_id TEXT NOT NULL DEFAULT '';

CREATE INDEX IF NOT EXISTS __DOCUMENTS_TABLE___owner_workspace_idx
  ON __DOCUMENTS_TABLE__ (owner_user_id, workspace_id);
